// Client & staff mock data for People & Team screens

export const mockClients = [
    {
        id: 'USR-9021',
        name: 'Aarav Sharma',
        phone: '+91 98765 43210',
        email: 'aarav.s@techcorp.in',
        tier: 'VIP Gold',
        joinedDate: '2026-01-10',
        totalBookings: 18,
        totalRevenue: 285000,
        kycStatus: 'Verified',
        kycDetail: 'Aadhaar & Driving License',
        topSegment: 'Luxury SUVs',
        currentBooking: { car: 'Mahindra Thar 4x4', status: 'Active', days: 5, rate: 4500 },
        pastBookingsCount: 17,
        recentNote: 'Frequent corporate client. Maintains 100% on-time return record.',
    },
    {
        id: 'USR-5512',
        name: 'Vikramjit Singh',
        phone: '+91 94455 66778',
        email: 'vikram.singh@logistics.in',
        tier: 'Tier 1 Elite',
        joinedDate: '2026-01-22',
        totalBookings: 14,
        totalRevenue: 240000,
        kycStatus: 'Verified',
        kycDetail: 'Driving License & Aadhaar',
        topSegment: 'Full-size 4x4',
        currentBooking: null,
        pastBookingsCount: 14,
        recentNote: 'High billing value per trip. Zero accident claims.',
    },
];

export const mockStaff = [
    {
        id: 'STF-001',
        name: 'Ramesh Kumar',
        role: 'Fleet Manager',
        phone: '+91 91234 11223',
        joinedDate: '2024-05-12',
        status: 'Active',
        salary: 45000,
        pendingPayout: 0,
        lastPayout: '2026-05-01',
        logs: [
            { date: '2026-05-01', type: 'Salary Credit', amount: 45000, status: 'Completed' },
            { date: '2026-04-01', type: 'Salary Credit', amount: 45000, status: 'Completed' },
        ],
        overview: 'Handles all daily dispatch operations and coordinates with mechanics.',
    },
    {
        id: 'STF-002',
        name: 'Suresh Yadav',
        role: 'Senior Mechanic',
        phone: '+91 99887 55443',
        joinedDate: '2025-01-10',
        status: 'Active',
        salary: 32000,
        pendingPayout: 5000,
        lastPayout: '2026-05-01',
        logs: [
            { date: '2026-05-15', type: 'Overtime Bonus', amount: 5000, status: 'Pending' },
            { date: '2026-05-01', type: 'Salary Credit', amount: 32000, status: 'Completed' },
        ],
        overview: 'Specialist in SUV engine diagnostics.',
    },
    {
        id: 'STF-003',
        name: 'Amit Patel',
        role: 'Delivery Driver',
        phone: '+91 88776 22334',
        joinedDate: '2025-08-22',
        status: 'On Leave',
        salary: 22000,
        pendingPayout: 0,
        lastPayout: '2026-05-01',
        logs: [
            { date: '2026-05-01', type: 'Salary Credit', amount: 22000, status: 'Completed' },
        ],
        overview: 'Responsible for car drops to client locations.',
    },
];
